### ISSUE TITLE
Can't connect to pocket (HTTP 500)

### ISSUE THREAD

**Issue by alex-boyko** [christian-putzke/freshrss-pocket-button#3]
It seems that the extension is not working with the latest snapshot of FreshRSS.

I *think* the commit [2038d50](https://github.com/FreshRSS/FreshRSS/commit/2038d50110468d95ff978ba2e8f997175f25ff3b) had changed the logic of Minz_Request forward. You can't pass a url string anymore. I'm getting the following error while trying to connect to Pocket:
```
PHP Fatal error:  Uncaught TypeError: Minz_Url::checkControllerUrl(): Argument #1 ($url) must be of type array, string given, called in /app/www/lib/Minz/Request.php on line 386 and defined in /app/www/lib/Minz/Url.php:117
Stack trace:
 #0 /app/www/lib/Minz/Request.php(386): Minz_Url::checkControllerUrl()
 #1 /config/www/freshrss/extensions/freshrss-pocket-button/Controllers/pocketButtonController.php(74): Minz_Request::forward()
 #2 /app/www/lib/Minz/Dispatcher.php(121): FreshExtension_pocketButton_Controller->requestAccessAction()
 #3 /app/www/lib/Minz/Dispatcher.php(50): Minz_Dispatcher->launchAction()
 #4 /app/www/lib/Minz/FrontController.php(60): Minz_Dispatcher->run()
 #5 /app/www/p/i/index.php(57): Minz_FrontController->run()
 #6 {main}
  thrown in /app/www/lib/Minz/Url.php on line 117" while reading response header from upstream
```

**Comment by christian-putzke** [comment]
Thanks for your report @alex-boyko :)
I just released a new version which fixes this issue.

**Comment by alex-boyko** [comment]
Thanks for the fix @christian-putzke! Confirmed to be working now.
